package com.sentinel.os

/**
 * BuildConfig is auto-generated by Gradle.
 * This is a placeholder for IDE recognition.
 */
object BuildConfig {
    const val DEBUG = true
    const val APPLICATION_ID = "com.sentinel.os"
    const val BUILD_TYPE = "debug"
    const val VERSION_CODE = 1
    const val VERSION_NAME = "1.0.0"
}
